version: "3"
services:
  web:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${PROJECT_PATH}:/work
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build: ./docker/php
    ports:
      - ${LARAVEL_SERVER_PORT}:8000
    volumes:
      - ${PROJECT_PATH}:/work
      - ./docker/ash:/etc/profile.d
      - ./logs:/var/log/php
    working_dir: /work

  composer:
    build: ./docker/composer
    volumes:
      - ${PROJECT_PATH}:/work
    working_dir: /work

  db:
    image: postgres:11
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
      - ./docker/db/initdb:/docker-entrypoint-initdb.d

volumes:
  db-data:
    driver: local
